import { ArrowUpRight, CalendarDays, ChevronRight, Clock3, Stethoscope, UsersRound } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useHospitalStore } from '@/lib/hospital-store';
import { PageHeader, StatTile, Avatar } from '@/components/hospital-ui';

const timeLabel = (value: string) => new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
const dateLabel = (value: string) => new Date(value).toLocaleDateString([], { weekday: 'short', month: 'short', day: 'numeric' });

export default function Overview() {
  const [, setLocation] = useLocation();
  const { departments, doctors, patients, appointments } = useHospitalStore();
  const today = appointments.slice(0, 4);
  const upcoming = appointments.slice(4);
  return <div className="page-enter"><PageHeader eyebrow="Tuesday · June 18, 2024" title="Good morning, Alex" description="Here’s the operational pulse for Harborview Medical Center." action={() => setLocation('/appointments')} actionLabel="Schedule appointment" />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatTile label="Departments" value={departments.length} detail="Across the hospital" icon={Stethoscope} accent="teal" /><StatTile label="Doctors" value={doctors.length} detail="Active medical staff" icon={UsersRound} accent="blue" /><StatTile label="Patients" value={patients.length} detail="Registered this quarter" icon={UsersRound} accent="green" /><StatTile label="Appointments" value={appointments.length} detail="6 scheduled this week" icon={CalendarDays} accent="amber" /></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <section className="surface overflow-hidden rounded-xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-[15px] font-bold">Today’s schedule</h2><p className="mt-0.5 text-[12px] text-muted-foreground">Four appointments need attention today</p></div><Link href="/appointments" data-testid="link-view-all-appointments" className="flex items-center gap-1 text-[12px] font-bold text-primary hover:underline">View all <ArrowUpRight size={14} /></Link></div><div className="divide-y divide-border">{today.map((appointment, index) => <div data-testid={`row-today-appointment-${appointment.id}`} key={appointment.id} className="group flex items-center gap-4 px-5 py-4 transition-colors hover:bg-background"><div className={`mono w-14 text-[11px] font-bold ${index === 0 ? 'text-primary' : 'text-muted-foreground'}`}>{timeLabel(appointment.appointmentDate)}</div><div className="h-9 w-px bg-border" /><Avatar name={appointment.patientName} tone={index % 2 ? 'blue' : 'teal'} /><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-bold">{appointment.patientName}</p><p className="mt-0.5 truncate text-[11px] text-muted-foreground">{appointment.description} <span className="mx-1 text-border">·</span> {appointment.departmentName}</p></div><div className="hidden text-right sm:block"><p className="text-[12px] font-semibold">{appointment.doctorName}</p><p className="mt-0.5 text-[11px] text-muted-foreground">Consultation</p></div><ChevronRight size={16} className="text-border transition-transform group-hover:translate-x-1 group-hover:text-primary" /></div>)}</div></section>
      <section className="surface overflow-hidden rounded-xl"><div className="border-b border-border px-5 py-4"><h2 className="text-[15px] font-bold">Coming up</h2><p className="mt-0.5 text-[12px] text-muted-foreground">Next appointments in your queue</p></div><div className="p-3">{upcoming.map((appointment) => <div data-testid={`card-upcoming-${appointment.id}`} key={appointment.id} className="rounded-lg p-3 transition-colors hover:bg-background"><div className="flex items-center justify-between"><span className="mono text-[10px] font-bold uppercase tracking-[.12em] text-primary">{dateLabel(appointment.appointmentDate)}</span><Clock3 size={14} className="text-muted-foreground" /></div><p className="mt-2 text-[13px] font-bold">{appointment.patientName}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{timeLabel(appointment.appointmentDate)} · {appointment.departmentName}</p></div>)}</div><Link href="/appointments" data-testid="link-upcoming-appointments" className="mx-5 mb-4 flex items-center justify-center gap-1 rounded-lg border border-border py-2 text-[12px] font-bold text-muted-foreground hover:bg-muted hover:text-primary">Open appointment board <ChevronRight size={14} /></Link></section>
    </div>
    <section className="mt-6 rounded-xl bg-[#e3f0ef] p-5 md:flex md:items-center md:justify-between md:px-6"><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#c7e4e1] text-primary"><Stethoscope size={18} /></div><div><p className="text-[13px] font-bold text-[#174f58]">Keep the floor moving</p><p className="mt-1 text-[12px] text-[#4a7478]">Your next handoff is in 42 minutes. All departments are currently within capacity.</p></div></div><Link href="/departments" data-testid="link-review-departments" className="mt-4 flex items-center gap-1 text-[12px] font-bold text-primary hover:underline md:mt-0">Review departments <ArrowUpRight size={14} /></Link></section>
  </div>;
}