import { useMemo, useState, type FormEvent } from 'react';
import { CalendarDays, ClipboardList, Filter, Stethoscope, UsersRound } from 'lucide-react';
import type { Appointment, Department, Doctor, Patient } from '@workspace/api-client-react';
import { useHospitalStore } from '@/lib/hospital-store';
import { Avatar, ConfirmModal, EmptyState, Field, FormFooter, Modal, PageHeader, RecordActions, SearchBox, SkeletonRows } from '@/components/hospital-ui';

type Mode = 'departments' | 'doctors' | 'patients' | 'appointments';
type FormState = { name: string; departmentId: string; registrationDate: string; appointmentDate: string; description: string; patientId: string; doctorId: string };
const blankForm: FormState = { name: '', departmentId: '', registrationDate: '2024-06-18', appointmentDate: '2024-06-19T09:00', description: '', patientId: '', doctorId: '' };
const config = {
  departments: { eyebrow: 'Directory / departments', title: 'Departments', description: 'Keep clinical teams mapped, named, and ready for the day.', singular: 'department', icon: ClipboardList },
  doctors: { eyebrow: 'Directory / medical staff', title: 'Doctors', description: 'A clear view of your active clinicians and their home departments.', singular: 'doctor', icon: Stethoscope },
  patients: { eyebrow: 'Directory / patient registry', title: 'Patients', description: 'Registration history and care activity, kept in one dependable place.', singular: 'patient', icon: UsersRound },
  appointments: { eyebrow: 'Care coordination / schedule', title: 'Appointments', description: 'Coordinate patient care across clinicians, departments, and time.', singular: 'appointment', icon: CalendarDays },
} as const;

export default function RecordsPage({ mode }: { mode: Mode }) {
  const store = useHospitalStore();
  const current = config[mode];
  const [search, setSearch] = useState('');
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<number | null>(null);
  const [deleting, setDeleting] = useState<{ id: number; label: string } | null>(null);
  const [form, setForm] = useState(blankForm);
  const [filter, setFilter] = useState('all');
  const records = mode === 'departments' ? store.departments : mode === 'doctors' ? store.doctors : mode === 'patients' ? store.patients : store.appointments;
  const isLoading = false;
  const filtered = useMemo(() => records.filter((record) => {
    const text = mode === 'departments' ? (record as Department).name : mode === 'doctors' ? `${(record as Doctor).name} ${(record as Doctor).departmentName}` : mode === 'patients' ? (record as Patient).name : `${(record as Appointment).patientName} ${(record as Appointment).doctorName} ${(record as Appointment).description}`;
    const filterMatch = filter === 'all' || (mode === 'doctors' && (record as Doctor).departmentId === Number(filter)) || (mode === 'appointments' && (record as Appointment).departmentName === filter);
    return text.toLowerCase().includes(search.toLowerCase()) && filterMatch;
  }), [records, search, filter, mode]);
  const setField = (key: keyof FormState, value: string) => setForm((old) => ({ ...old, [key]: value }));
  const openCreate = () => { setEditing(null); setForm({ ...blankForm }); setFormOpen(true); };
  const openEdit = (record: Department | Doctor | Patient | Appointment) => {
    setEditing(record.id);
    if (mode === 'departments') setForm({ ...blankForm, name: (record as Department).name });
    if (mode === 'doctors') { const item = record as Doctor; setForm({ ...blankForm, name: item.name, departmentId: String(item.departmentId) }); }
    if (mode === 'patients') { const item = record as Patient; setForm({ ...blankForm, name: item.name, registrationDate: item.registrationDate }); }
    if (mode === 'appointments') { const item = record as Appointment; setForm({ ...blankForm, appointmentDate: item.appointmentDate.slice(0, 16), description: item.description, patientId: String(item.patientId), doctorId: String(item.doctorId) }); }
    setFormOpen(true);
  };
  const save = (event: FormEvent) => {
    event.preventDefault();
    if (mode === 'departments' && form.name.trim()) editing ? store.updateDepartment(editing, form.name.trim()) : store.addDepartment(form.name.trim());
    if (mode === 'doctors' && form.name.trim() && form.departmentId) editing ? store.updateDoctor(editing, form.name.trim(), Number(form.departmentId)) : store.addDoctor(form.name.trim(), Number(form.departmentId));
    if (mode === 'patients' && form.name.trim() && form.registrationDate) editing ? store.updatePatient(editing, form.name.trim(), form.registrationDate) : store.addPatient(form.name.trim(), form.registrationDate);
    if (mode === 'appointments' && form.description.trim() && form.patientId && form.doctorId) editing ? store.updateAppointment(editing, form.appointmentDate, form.description.trim(), Number(form.patientId), Number(form.doctorId)) : store.addAppointment(form.appointmentDate, form.description.trim(), Number(form.patientId), Number(form.doctorId));
    setFormOpen(false);
  };
  const remove = () => { if (!deleting) return; if (mode === 'departments') store.removeDepartment(deleting.id); if (mode === 'doctors') store.removeDoctor(deleting.id); if (mode === 'patients') store.removePatient(deleting.id); if (mode === 'appointments') store.removeAppointment(deleting.id); setDeleting(null); };
  return <div className="page-enter"><PageHeader eyebrow={current.eyebrow} title={current.title} description={current.description} action={openCreate} actionLabel={`Add ${current.singular}`} />
    <div className="surface overflow-hidden rounded-xl">
      <div className="flex flex-col gap-3 border-b border-border p-4 md:flex-row md:items-center md:justify-between"><div className="w-full md:max-w-[330px]"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${current.title.toLowerCase()}…`} /></div><div className="flex items-center gap-2"><div className="relative"><Filter size={14} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><select data-testid="select-record-filter" value={filter} onChange={(event) => setFilter(event.target.value)} className="h-10 appearance-none rounded-lg border border-border bg-background pl-9 pr-8 text-[12px] font-medium outline-none focus:border-primary"><option value="all">All {current.title.toLowerCase()}</option>{mode === 'doctors' && store.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}{mode === 'appointments' && store.departments.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></div><span className="mono hidden text-[10px] uppercase tracking-[.12em] text-muted-foreground sm:block">{filtered.length} records</span></div></div>
      {isLoading ? <SkeletonRows /> : filtered.length === 0 ? <EmptyState title={search ? 'No matching records' : `No ${current.title.toLowerCase()} yet`} description={search ? 'Try a different search term or clear your filters.' : `Add a ${current.singular} to start organizing this workspace.`} action={openCreate} /> : <div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse"><thead><tr className="border-b border-border bg-background/60 text-left"><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Record</th>{mode === 'departments' && <th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Doctors</th>}{mode === 'doctors' && <th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Department</th>}{mode === 'patients' && <><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Registered</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Appointments</th></>}{mode === 'appointments' && <><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">When</th><th className="px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Care team</th></>}<th className="px-5 py-3 text-right text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">Actions</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((record, index) => {
        const department = record as Department; const doctor = record as Doctor; const patient = record as Patient; const appointment = record as Appointment;
        return <tr data-testid={`row-${mode}-${record.id}`} key={record.id} className="group transition-colors hover:bg-background"><td className="px-5 py-4"><div className="flex items-center gap-3"><Avatar name={mode === 'departments' ? department.name : mode === 'doctors' ? doctor.name : mode === 'patients' ? patient.name : appointment.patientName} tone={(['teal', 'blue', 'green', 'amber'] as const)[index % 4]} /><div><p className="text-[13px] font-bold">{mode === 'departments' ? department.name : mode === 'doctors' ? doctor.name : mode === 'patients' ? patient.name : appointment.patientName}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{mode === 'departments' ? `Department ID · ${department.id.toString().padStart(3, '0')}` : mode === 'doctors' ? `Medical staff ID · ${doctor.id.toString().padStart(3, '0')}` : mode === 'patients' ? `Patient ID · ${patient.id.toString().padStart(3, '0')}` : appointment.description}</p></div></div></td>{mode === 'departments' && <td className="px-5 py-4"><span className="rounded-full bg-secondary px-2.5 py-1 text-[11px] font-bold text-secondary-foreground">{department.doctorCount} clinicians</span></td>}{mode === 'doctors' && <td className="px-5 py-4 text-[12px] font-medium text-muted-foreground">{doctor.departmentName}</td>}{mode === 'patients' && <><td className="px-5 py-4 text-[12px] text-muted-foreground">{new Date(patient.registrationDate).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}</td><td className="px-5 py-4"><span className="mono text-[12px] font-bold text-primary">{patient.appointmentCount.toString().padStart(2, '0')}</span></td></>}{mode === 'appointments' && <><td className="px-5 py-4"><p className="text-[12px] font-bold">{new Date(appointment.appointmentDate).toLocaleDateString([], { month: 'short', day: 'numeric' })}</p><p className="mono mt-1 text-[10px] text-primary">{new Date(appointment.appointmentDate).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</p></td><td className="px-5 py-4"><p className="text-[12px] font-semibold">{appointment.doctorName}</p><p className="mt-1 text-[11px] text-muted-foreground">{appointment.departmentName}</p></td></>}<td className="px-5 py-4"><RecordActions id={record.id} onEdit={() => openEdit(record)} onDelete={() => setDeleting({ id: record.id, label: mode === 'appointments' ? appointment.patientName : mode === 'departments' ? department.name : mode === 'doctors' ? doctor.name : patient.name })} /></td></tr>;
      })}</tbody></table></div>}
    </div>
    {formOpen && <Modal title={`${editing ? 'Edit' : 'Add'} ${current.singular}`} subtitle={`Update the ${current.singular} record below.`} onClose={() => setFormOpen(false)}><form onSubmit={save} className="space-y-4">
      {(mode === 'departments' || mode === 'doctors' || mode === 'patients') && <Field label={mode === 'departments' ? 'Department name' : mode === 'doctors' ? 'Doctor name' : 'Patient name'}><input autoFocus required data-testid="input-record-name" value={form.name} onChange={(event) => setField('name', event.target.value)} placeholder={mode === 'departments' ? 'e.g. Emergency medicine' : mode === 'doctors' ? 'e.g. Dr. Helen Brooks' : 'e.g. Jordan Lee'} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary focus:ring-2 focus:ring-primary/10" /></Field>}
      {mode === 'doctors' && <Field label="Department"><select required data-testid="select-doctor-department" value={form.departmentId} onChange={(event) => setField('departmentId', event.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary"><option value="">Choose a department</option>{store.departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}
      {mode === 'patients' && <Field label="Registration date"><input required type="date" data-testid="input-registration-date" value={form.registrationDate} onChange={(event) => setField('registrationDate', event.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary" /></Field>}
      {mode === 'appointments' && <><Field label="Patient"><select required data-testid="select-appointment-patient" value={form.patientId} onChange={(event) => setField('patientId', event.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary"><option value="">Choose a patient</option>{store.patients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Doctor"><select required data-testid="select-appointment-doctor" value={form.doctorId} onChange={(event) => setField('doctorId', event.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary"><option value="">Choose a doctor</option>{store.doctors.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.departmentName}</option>)}</select></Field><Field label="Date and time"><input required type="datetime-local" data-testid="input-appointment-date" value={form.appointmentDate} onChange={(event) => setField('appointmentDate', event.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-[13px] outline-none focus:border-primary" /></Field><Field label="Appointment description"><textarea required data-testid="input-appointment-description" value={form.description} onChange={(event) => setField('description', event.target.value)} placeholder="What is this visit for?" rows={3} className="w-full resize-none rounded-lg border border-border bg-background px-3 py-2 text-[13px] outline-none focus:border-primary" /></Field></>}
      <FormFooter onClose={() => setFormOpen(false)} />
    </form></Modal>}
    {deleting && <ConfirmModal title={`Delete ${current.singular}?`} description={`You are about to permanently delete ${deleting.label}. Existing relationships may need to be reviewed.`} onConfirm={remove} onClose={() => setDeleting(null)} />}
  </div>;
}